[mongodb]
mongodb.manibhargavi2225.online

[redis]
redis.manibhargavi2225.online

[mysql]
mysql.manibhargavi2225.online

[rabbitmq]
rabbitmq.manibhargavi2225.online

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory

 