[mongodb]
mongodb.manibhargavi225.online

[redis]
redis.manibhargavi225.online

[mysql]
mysql.manibhargavi225.online

[rabbitmq]
rabbitmq.manibhargavi225.online

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory

 